- hosts: all
  become: yes
  vars:
    - deployment: "vagrant"
  tasks:
    - name: setting network fact (Vagrant)
      set_fact: 
        ipv4address: "{{ ansible_enp0s8.ipv4.address }}"
      when: 'deployment == "vagrant"'

    - name: setting network fact (Other)
      set_fact: 
        ipv4address: "{{ ansible_enp0s8.ipv4.address }}"
      when: 'deployment != "vagrant"'

    - debug:
        msg: "{{ ipv4address }}"


- hosts: all
  become: yes
  tasks:
   - debug:
        msg: "{{ ipv4address }}"