---
# tasks file for httpd
- name: install httpd
  yum: name=httpd state=present

- name: enable & start httpd
  service: name=httpd state=started enabled=true

- name: create kube version dir
  file: path=/var/www/html/kubernetes/{{ kubernetes_version }} state=directory

- name: get kubelet
  get_url: 
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/{{ arch }}/{{ item }}"
    dest: "/var/www/html/kubernetes/{{ kubernetes_version }}/{{ item }}"
  retries: 5
  register: get_url_result
  until: get_url_result | succeeded
  with_items:
    - kubelet

- name: create calico version dir
  file: path=/var/www/html/calico/{{ calico_version }} state=directory

- name: get calico files
  get_url: 
    url: "https://github.com/projectcalico/calico-cni/releases/download/{{ calico_version }}/{{ item }}"
    dest: "/var/www/html/calico/{{ calico_version }}/{{ item }}"
  retries: 5
  register: get_url_result
  until: get_url_result | succeeded
  with_items:
    - calico
    - calico-ipam

- name: create cni dir
  file: path=/var/www/html/cni/ state=directory

- name: get cni bins
  get_url: 
    url: "https://github.com/containernetworking/cni/releases/download/{{ cni_version }}/cni-{{ arch }}-{{ cni_version }}.tgz"
    dest: "/var/www/html/cni/cni-{{ cni_version }}.tgz"
  retries: 5
  register: get_url_result
  until: get_url_result | succeeded

- name: create flannel dir
  file: path=/var/www/html/flannel/{{ flannel_version }} state=directory

- name: download flannel binaries
  get_url:
    url: "https://github.com/coreos/flannel/releases/download/{{ flannel_version }}/flannel-{{ flannel_version }}-linux-{{ arch }}.tar.gz"
    dest: /var/www/html/flannel/{{ flannel_version }}/flannel-{{ flannel_version }}-linux-{{ arch }}.tar.gz
  retries: 5
  register: get_url_result
  until: get_url_result | succeeded



