---
# tasks file for httpd
- name: install httpd
  yum: name=httpd state=present

- name: enable & start httpd
  service: name=httpd state=started enabled=true

- name: create kube version dir
  file: path=/var/www/html/kubernetes/{{ kubernetes_version }} state=directory

- name: get kubelet
  get_url: 
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/amd64/{{ item }}"
    dest: "/var/www/html/kubernetes/{{ kubernetes_version }}/{{ item }}"
  with_items:
    - kubelet
    - kube-apiserver
    - kube-proxy

- name: create calico version dir
  file: path=/var/www/html/calico/{{ calico_version }} state=directory

- name: get calico files
  get_url: 
    url: "https://github.com/projectcalico/calico-cni/releases/download/{{ calico_version }}/{{ item }}"
    dest: "/var/www/html/calico/{{ calico_version }}/{{ item }}"
  with_items:
    - calico
    - calico-ipam

- name: get cni lo
  get_url: 
    url: "https://github.com/containernetworking/cni/releases/download/v0.3.0/cni-v0.3.0.tgz"
    dest: "/var/www/html/calico/cni-v0.3.0.tgz"