---
# tasks file for etcd

- name: create kubelet manifest folder
  file: path=/etc/kubelet.d state=directory

- name: put etcd in kubeletfolder
  template: src=etcd.yaml.j2 dest=/etc/kubelet.d/etcd.yaml
  when: "ansible_hostname == hostvars[groups['managers'][0]]['ansible_hostname']"

- wait_for:
    host: "{{ ansible_enp0s8.ipv4.address }}"
    port: 2380
    delay: 10
  when: "ansible_hostname == hostvars[groups['managers'][0]]['ansible_hostname']"

- wait_for:
    host: "{{ ansible_enp0s8.ipv4.address }}"
    port: 2379
  when: "ansible_hostname == hostvars[groups['managers'][0]]['ansible_hostname']"

- name: retrieve etcd_memberlist
  shell: docker exec -i `docker ps -q --filter label=io.kubernetes.container.name=etcd` etcdctl --endpoints=https://{{ hostvars[groups['managers'][0]]['ansible_enp0s8']['ipv4']['address'] }}:2379 --ca-file=/etc/kubernetes/ssl/ca.pem member list
  changed_when: False
  delegate_to: "{{ groups['managers'][0] }}"
  register: etcd_members

- debug:
    msg: "{{ etcd_members.stdout_lines }}"

- name: adding secondary manager to etcd cluster
  shell: docker exec -i `docker ps -q --filter label=io.kubernetes.container.name=etcd` etcdctl --endpoints=https://{{ hostvars[groups['managers'][0]]['ansible_enp0s8']['ipv4']['address'] }}:2379 --ca-file=/etc/kubernetes/ssl/ca.pem member add {{ ansible_hostname }} https://{{ ansible_enp0s8.ipv4.address }}:2380
  delegate_to: "{{ groups['managers'][0] }}"
  register: etcd_data
  when: "{{ groups['managers'] | length }} > 1 and ansible_hostname != hostvars[groups['managers'][0]]['ansible_hostname'] and 
        etcd_members.stdout.find( ansible_hostname ) == -1" 

- debug:
    msg: "{{ etcd_data.stdout_lines }}"
  when: "{{ groups['managers'] | length }} > 1 and ansible_hostname != hostvars[groups['managers'][0]]['ansible_hostname'] and 
        etcd_members.stdout.find( ansible_hostname ) == -1" 

- name: put etcd in kubeletfolder
  template: src=etcd-secondary.yaml.j2 dest=/etc/kubelet.d/etcd.yaml
  when: "ansible_hostname != hostvars[groups['managers'][0]]['ansible_hostname']"

- name: etcdctl alias in profile
  lineinfile: 
    dest: /root/.bash_profile
    line: "alias etcdctl=\"docker exec -it 
          $(docker ps -q --filter label=io.kubernetes.container.name=etcd)
          etcdctl --endpoints=https://172.16.50.11:2379 --ca-file=/etc/kubernetes/ssl/ca.pem\""
