docker_images:
  - "quay.io/coreos/etcd:{{ etcd_version }}"
  - "gcr.io/google_containers/hyperkube-{{ arch }}:{{ kubernetes_version }}"
  - "gcr.io/google_containers/kube-dnsmasq-amd64:1.4"
  - "gcr.io/google_containers/exechealthz-amd64:1.2"
  - "gcr.io/google_containers/kubedns-amd64:1.8"

  # - "quay.io/coreos/flannel:{{ flannel_version }}"
  # - "quay.io/calico/node:{{ calico_node_version }}"
  # - "calico/cni:{{ calico_cni_version }}"
  # - "calico/kube-policy-controller:{{ calico_kpc_version }}"

arch: amd64
etcd_version: v3.0.16
kubernetes_version: v1.5.2
flannel_version: v0.7.0
calico_version: v1.5.5
calico_node_version: v1.0.0
cni_version: v0.4.0

calico_cni_version: v1.5.5
calico_kpc_version: v0.5.1

POD_NETWORK: "10.2.0.0/16"
SERVICE_IP_RANGE: "10.3.0.0/24"
K8S_SERVICE_IP: "10.3.0.1"
DNS_SERVICE_IP: "10.3.0.10"

loglevel: 2
kube_token: DeevDJEMJnxQPb4Pse9QHBWt
kube_config: /etc/kubernetes/kubeconfig.yaml

proxy_mode: iptables