---
# tasks file for docker
- name: install docker-repo
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo mode=644

- name: install docker
  yum: name=docker-engine state=present
  retries: 5
  register: yum_docker_result
  until: yum_docker_result | succeeded


- name: install other docker dependencies for ansible
  include: dependencies.yaml

- name: create docker service.d dir
  file: dest=/etc/systemd/system/docker.service.d state=directory mode=755

- name: retrieve facts (needed to fill config file of docker (insecure registry))
  setup: 
  delegate_to: "{{ groups['managers'][0] }}"
  delegate_facts: True

- name: add docker config
  template: src=docker.conf.j2 dest=/etc/systemd/system/docker.service.d/docker.conf mode=644
  notify:
    - restart docker

- name: docker service starten en enablen
  service: name=docker enabled=yes state=started

- name: add br_netfilter to rc.modules
  lineinfile: dest=/etc/rc.modules line=br_netfilter state=present create=yes

- name: create /etc/rc/modules
  file: path=/etc/rc.modules state=file mode=755 owner=root

- name: load br_netfilter
  modprobe: name=br_netfilter state=present

- name: triggering handlers
  meta: flush_handlers