---
- hosts: all
  become: yes
  tasks:
    - name: disable selinux
      selinux:
        state: disabled
    - name: "setting network fact (Vagrant: enp0s8, otherwise enp0s3)"
      set_fact: 
        ipv4address: "{{ ansible_enp0s8.ipv4.address }}"
        
- hosts: manager1
  become: yes
  roles:
    - httpd

- hosts: managers
  become: yes
  roles:
    - ntp    
    - pki
    - docker
    - docker-registry
    - kubelet
    
- hosts: managers
  become: yes
  serial: 1
  roles:   
    - etcd

- hosts: managers
  become: yes
  roles:
    - kube-manager
    - canal

- hosts: workers
  become: yes
  roles:
    - ntp
    - pki
    - docker
    - kubelet
    - kube-worker
    - canal

- hosts: manager1
  become: yes
  roles:
    - kubedns
