---
# tasks file for kube-manager

- include: kubelet.yaml

- debug:
    msg: "http://{{ groups['managers'] | map('extract', hostvars, ['ansible_enp0s8', 'ipv4', 'address']) | join(':2379,http://') }}:2379"


- name: copy apiserver.yaml to kubelet
  template: src=kube-apiserver.yaml.j2 dest=/etc/kubelet.d/kube-apiserver.yaml
